### ISSUE TITLE
Index Page Has No Favicon

### ISSUE THREAD

**Issue by polerizer** [Landships/Website#2]
The index page currently has no favicon. We can specify a favicon for this subdomain in two ways:

1. We can create a `landships.vrab.io/favicon.ico`, but this requires you to use a `.ico` file, which can be limiting.

2. We can include a tag in `<head>` that specifies the favicon, which is nicer since we can use most image file types as opposed to just ico.

If you guys don't have a favicon of your own, we can also link to the VR logo favicon we use on vrab.io

**Comment by Landships** [comment]
Not sure if it works now, I don't see anything in chrome locally

**Comment by Landships** [comment]
I think it works 
![image](https://cloud.githubusercontent.com/assets/22580205/23541520/c62995e6-ff9c-11e6-8aa8-6509c2fcb769.png)
